# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir V:/Projects/32BitProcessor/32BitProcessor.cache/wt [current_project]
set_property parent.project_path V:/Projects/32BitProcessor/32BitProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo v:/Projects/32BitProcessor/32BitProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/ALU32Bit.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/BranchModule.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Controller.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/DataMemory.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/ForwardingUnit.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/HazardControl.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/HiLoReg.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/InstructionMemory.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/LowerHalfExtender.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/MovComponent.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Mux1Bit2To1.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Mux25Bit2To1.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Mux32Bit2To1.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Mux32Bit4To1.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Mux32To1.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Mux5Bit2To1.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/PCAdder.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/PipelineRegEX_MEM.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/PipelineRegID_EX.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/PipelineRegIF_ID.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/PipelineRegMEM_WB.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/ProgramCounter.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/RegisterFile.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/RotateRight.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/SignExtendByte.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/SignExtension.v
  V:/Projects/32BitProcessor/32BitProcessor.srcs/sources_1/imports/new/Datapath.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc V:/Projects/32BitProcessor/32BitProcessor.srcs/constrs_1/imports/new/const.xdc
set_property used_in_implementation false [get_files V:/Projects/32BitProcessor/32BitProcessor.srcs/constrs_1/imports/new/const.xdc]


synth_design -top Datapath -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Datapath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Datapath_utilization_synth.rpt -pb Datapath_utilization_synth.pb"
